import { createServer } from "node:http";
import { createReadStream, existsSync, statSync } from "node:fs";
import { extname, join, normalize } from "node:path";
import { randomBytes } from "node:crypto";
const port=Number(process.env.PORT||3000),root=process.cwd(),rooms=new Map();
const types={".css":"text/css; charset=utf-8",".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".json":"application/json; charset=utf-8",".svg":"image/svg+xml"},wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
function newRoom(){const id=randomBytes(3).toString("hex");rooms.set(id,{id,board:Array(9).fill(null),turn:"X",winner:null,winningCells:[],players:{X:null,O:null},scores:{X:0,O:0},rematchVotes:[]});return rooms.get(id);}function state(room,sessionId){const you=room.players.X===sessionId?"X":room.players.O===sessionId?"O":null;return{roomId:room.id,board:room.board,turn:room.turn,winner:room.winner,winningCells:room.winningCells,scores:room.scores,players:{X:Boolean(room.players.X),O:Boolean(room.players.O)},rematchVotes:room.rematchVotes.map(id=>id===room.players.X?"X":id===room.players.O?"O":null).filter(Boolean),you};}function send(res,code,body){res.writeHead(code,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(body));}function read(req){return new Promise((resolve,reject)=>{let body="";req.on("data",c=>body+=c);req.on("end",()=>{try{resolve(body?JSON.parse(body):{});}catch{reject();}});});}function evaluate(room){const row=wins.find(([a,b,c])=>room.board[a]&&room.board[a]===room.board[b]&&room.board[a]===room.board[c]);if(row){room.winner=room.board[row[0]];room.winningCells=row;room.scores[room.winner]+=1;}else if(room.board.every(Boolean))room.winner="draw";}function reset(room){room.board=Array(9).fill(null);room.turn=room.winner==="O"?"X":"O";room.winner=null;room.winningCells=[];room.rematchVotes=[];}
const server=createServer(async(req,res)=>{const url=new URL(req.url||"/",`http://${req.headers.host||"localhost"}`),parts=url.pathname.split("/").filter(Boolean);if(parts[0]==="api"){try{if(req.method==="POST"&&parts[1]==="rooms"&&!parts[2]){const room=newRoom();return send(res,201,{roomId:room.id});}const room=rooms.get(parts[2]);if(!room)return send(res,404,{error:"Room not found"});if(req.method==="POST"&&parts[3]==="join"){const{sessionId}=await read(req);if(!sessionId)return send(res,400,{error:"Missing player session"});if(!Object.values(room.players).includes(sessionId)){if(!room.players.X)room.players.X=sessionId;else if(!room.players.O)room.players.O=sessionId;}return send(res,200,state(room,sessionId));}if(req.method==="GET"&&!parts[3])return send(res,200,state(room,url.searchParams.get("sessionId")));const body=await read(req),mark=room.players.X===body.sessionId?"X":room.players.O===body.sessionId?"O":null;if(!mark)return send(res,403,{error:"Spectators cannot make moves"});if(req.method==="POST"&&parts[3]==="move"){const cell=body.cell;if(room.winner||room.turn!==mark||!Number.isInteger(cell)||cell<0||cell>8||room.board[cell])return send(res,409,{error:"That move is unavailable"});room.board[cell]=mark;evaluate(room);if(!room.winner)room.turn=mark==="X"?"O":"X";return send(res,200,state(room,body.sessionId));}if(req.method==="POST"&&parts[3]==="rematch"){if(!room.rematchVotes.includes(body.sessionId))room.rematchVotes.push(body.sessionId);if(room.rematchVotes.includes(room.players.X)&&room.rematchVotes.includes(room.players.O))reset(room);return send(res,200,state(room,body.sessionId));}return send(res,404,{error:"Not found"});}catch{return send(res,400,{error:"Invalid request"});}}const pathname=url.pathname==="/"?"/index.html":url.pathname,file=join(root,normalize(pathname).replace(/^(\.\.[/\\])+/,""));if(!existsSync(file)||statSync(file).isDirectory()){res.writeHead(404);return res.end("Not found");}res.writeHead(200,{"Content-Type":types[extname(file)]||"application/octet-stream"});createReadStream(file).pipe(res);});
server.listen(port,"0.0.0.0",()=>console.log(`XO game available at http://localhost:${port}`));
