const $ = (selector) => document.querySelector(selector);
const home = $("#home-screen"), game = $("#game-screen"), board = $("#board"), cells = [...board.querySelectorAll("button")];
const params = new URLSearchParams(location.search); let roomId = params.get("room"), sessionId = "", snapshot = null;
$("#create-room").addEventListener("click", createRoom); $("#join-form").addEventListener("submit", joinByCode); $("#copy-link").addEventListener("click", shareRoom); $("#share-button").addEventListener("click", shareRoom); $("#rematch-button").addEventListener("click", requestRound);
cells.forEach((cell) => cell.addEventListener("click", () => playMove(Number(cell.dataset.cell)))); if (roomId) openRoom();
async function createRoom(){try{const data=await api("/api/rooms",{method:"POST"});location.href=`/?room=${data.roomId}`;}catch{toast("Could not create a room. Try again.");}}
function joinByCode(event){event.preventDefault();const code=$("#room-input").value.trim().toLowerCase();if(!/^[a-f0-9]{6}$/.test(code)){toast("Enter the six-character room code.");return;}location.href=`/?room=${code}`;}
async function openRoom(){home.classList.add("hidden");game.classList.remove("hidden");sessionId=localStorage.getItem(`xo-session-${roomId}`)||crypto.randomUUID();localStorage.setItem(`xo-session-${roomId}`,sessionId);try{await api(`/api/rooms/${roomId}/join`,{method:"POST",body:JSON.stringify({sessionId})});await refresh();window.setInterval(refresh,1200);}catch{toast("This game room no longer exists.");}}
async function refresh(){try{snapshot=await api(`/api/rooms/${roomId}?sessionId=${encodeURIComponent(sessionId)}`);render();$("#connection-status").textContent="Live room";}catch{$("#connection-status").textContent="Reconnecting";}}
function render(){const {board:positions,players,turn,winner,winningCells,you,scores}=snapshot;$("#room-code").textContent=roomId.toUpperCase();$("#score-x").textContent=scores.X;$("#score-o").textContent=scores.O;renderPlayer("x",players.X,you==="X");renderPlayer("o",players.O,you==="O");cells.forEach((cell,i)=>{const mark=positions[i];cell.textContent=mark||"";cell.className=mark?`mark-${mark.toLowerCase()}`:"";if((winningCells||[]).includes(i))cell.classList.add("winning");cell.disabled=Boolean(mark||winner||!you||you!==turn||!players.X||!players.O);});let message="";if(!players.O)message="Waiting for a friend";else if(winner==="draw")message="It’s a draw";else if(winner)message=winner===you?"You win!":`${winner} wins`;else message=turn===you?"Your turn":"Their turn";$("#turn-message").textContent=message;const votes=snapshot.rematchVotes||[];$("#round-note").textContent=winner?(votes.includes(you)?"Waiting for the other player…":"Ready for another round?"):(you?`You’re playing as ${you}`:"You’re watching this round.");$("#rematch-button").textContent=winner?"Play again":"New round";}
function renderPlayer(mark,player,isYou){const el=$(`#player-${mark}`),name=el.querySelector("b"),sub=el.querySelector("small");el.classList.toggle("active",Boolean(player));if(!player){name.textContent="Open seat";sub.textContent="Invite a friend";return;}name.textContent=isYou?"You":"Opponent";sub.textContent=mark.toUpperCase()==="X"?"First move":"Second move";}
async function playMove(cell){try{snapshot=await api(`/api/rooms/${roomId}/move`,{method:"POST",body:JSON.stringify({sessionId,cell})});render();}catch(e){toast(e.message||"That move is unavailable.");}}
async function requestRound(){try{snapshot=await api(`/api/rooms/${roomId}/rematch`,{method:"POST",body:JSON.stringify({sessionId})});render();}catch(e){toast(e.message||"Only players can start a round.");}}
async function shareRoom(){const link=location.href;try{if(navigator.share)await navigator.share({title:"Join my XO game",text:"Play Tic-Tac-Toe with me",url:link});else{await navigator.clipboard.writeText(link);toast("Invite link copied!");}}catch{}}
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options});const data=await response.json();if(!response.ok)throw new Error(data.error);return data;}function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("visible");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("visible"),2600);}
